version: "3.9"


services:
  web:
    tty: true
    build: .
    command: sh -c " 
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/project_name # Same as in WORKIDIR inside of Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


volumes:
  postgres_data:
